project:
  type: website
  output-dir: docs
  
website:
  title: "RJ Dela Peña"
  search: false
  navbar:
    right:
      - text: "HOME"
        file: index.qmd
      - text: "PROJECTS"
        file: projects.qmd
      - text: "ABOUT"
        file: about.qmd        

  page-footer:
    right: "Built with [Quarto](https://quarto.org/)"
    left: "&copy; Copyright 2024, Ray John Dela Peña"

format:
  html:
    theme: flatly
    toc: false

editor: source

